### ISSUE TITLE
Licence File

### ISSUE THREAD

**Issue by antonlacon** [raspberrypi/utils#19]
There isn't a LICENCE file at the base like the userland repo, and `vclog/vcdbg.c` doesn't appear to have a licence specified at its top. Is it safe to assume it's BSD-3-Clause like the others?

**Comment by popcornmix** [comment]
Yes, the intention is for this code to be BSD 3-clause, but it appears the overall licence is missing.

@pelwell Okay to add https://github.com/raspberrypi/userland/blob/master/LICENCE (probably minus the Broadcom part) to the top level here? I think this repo is all RPi created code.
