### ISSUE TITLE
Is there a reliable way to confirm that vclog is working?

### ISSUE THREAD

**Issue by jorisvergeer** [raspberrypi/utils#28]
I am experiencing issues with video decoding on the latest raspberry pi OS 64bit in the raspberry pi 3 with the default VC4 KMS overlay. And I want to investigate it from any possible angle. 

To get the VC to log anything I tried to trigger something with either permutation of start_debug=1 and/or start_x=1 in the config.txt.

But vclog always returns empty without any error. No messages and no asserts. 

Does this indicate that there is literally nothing to log, or that retrieving of the logs does not work?

**Comment by pelwell** [comment]
vclog should be working now on Pi 3 with the latest kernel.
