### ISSUE TITLE
dtoverlay-pre dtoverlay-post scripts obsolete

### ISSUE THREAD

**Issue by XECDesign** [raspberrypi/utils#47]
I've just checked with Simon and the commands those scripts run no longer do anything. So I'm guessing they should be removed?

**Comment by pelwell** [comment]
Deleting them would make the CMakeLists simple, and the app shouldn't mind.

**Comment by pelwell** [comment]
Have you tried without them?

**Comment by XECDesign** [comment]
I haven't but yeah, while rummaging through the repo I noticed that dtoverlay should be okay whether or not the files exist.

**Comment by XECDesign** [comment]
New raspi-utils package seems to work as expected. I'll leave it in the internal repo for a bit and make it public near the end of the week if there are no issues.
