### ISSUE TITLE
 error in vcgencmd man page

### ISSUE THREAD

**Issue by villeneuve** [raspberrypi/utils#53]
Hi
In the **vcgencmd man page**, the horizontal bit table (under the sentence: " Adding the bit numbers along the top we get") is showing 19 bits and starting with bit 1 instead of showing 20 bits and starting with bit 0.
It's minor but confusing (I've been confused)
It has been discussed in the [forum here](https://forums.raspberrypi.com/viewtopic.php?t=358602)

It is:

              19   18   17   16   15   14   13   12   11   10   9   8   7   6   5   4   3   2   1
               0    1    0    1    0    0    0    0    0    0   0   0   0   0   0   0   0   0   0

It should be:

              19   18   17   16   15   14   13   12   11   10   9   8   7   6   5   4   3   2   1   0
               0    1    0    1    0    0    0    0    0    0   0   0   0   0   0   0   0   0   0   0

Thank you

**Comment by Al-** [comment]
I support this correction (I've been confused, too)
