### ISSUE TITLE
Clarification request for pinctrl

### ISSUE THREAD

**Issue by seamusdemora** [raspberrypi/utils#58]
In the README for `pinctrl` is the following statement: 

>Splitting into a general gpiolib library and a separate client application allows new applications to be added easily. 

What is meant by "new applications" exactly? Could you give a brief example? (Apologies - not much of a C programmer).

**Comment by pelwell** [comment]
Applications which aren't pinctrl.

**Comment by seamusdemora** [comment]
Thank you for that supercilious answer :)

**Comment by seamusdemora** [comment]
"completed" in the sense that insults have been swapped   :)
