### ISSUE TITLE
Add `#define _GNU_SOURCE` so pinctrl builds on earlier glibc?

### ISSUE THREAD

**Issue by 6by9** [raspberrypi/utils#68]
Noted on https://forums.raspberrypi.com/viewtopic.php?t=364773 that pinctrl won't build on Buster. `reallocarray` was only added to the standard glibc in 2.29.

Adding `#define _GNU_SOURCE` gets it building, but do we care enough for the obsolete releases?

**Comment by pelwell** [comment]
Fixed by https://github.com/raspberrypi/utils/commit/e43a8e2b90405bf99678d629fc3b42a4337e35bb.
