### ISSUE TITLE
vcdbg gdrive rate limits

### ISSUE THREAD

**Issue by acostach** [raspberrypi/utils#70]
Hi @pelwell , in our automated tests for balenaOS we're pulling the statically pre-compiled 32bit version of `vcdbg`, which you shared in https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/67 . Unfortunately it looks like Gdrive has some rate-limiting and this causes our tests to fail.

```
root@9d6521e:/tmp# ./vcdbg log msg
./vcdbg: line 1: syntax error near unexpected token `<'
./vcdbg: line 1: `<!DOCTYPE html><html><head><title>Google Drive - Quota exceeded</title>
```

Could you please let me know if there's a different location from where it can be downloaded, eventually without rate limits?

Thank you

**Comment by pelwell** [comment]
There are two answers to this:
1. vcdbg is dead - use vclog, which you can build yourself (https://github.com/raspberrypi/utils/tree/master/vclog).
2. Feel free to copy that statically linked binary anywhere you want so that it isn't rate-limited.

**Comment by acostach** [comment]
Thank you!
