### ISSUE TITLE
Is it possible to read values from ADCs with pinctrl?

### ISSUE THREAD

**Issue by rafael2k** [raspberrypi/utils#76]
I realize that with vcgencmd I can read some ADC values in the Pi 5. Can the same be done through pinctrl?

**Comment by pelwell** [comment]
Rafael, the short answer is no. The slightly longer answer is no and, even if you could, it wouldn't be of much use unless you want to monitor VBUS because they are dedicated pins on RP1 (you can't enable ADC on regular GPIOs) and the Pi 5 board design doesn't make the spare channels available.

If you are still curious, the ADC values can be read from sysfs:
```
$ grep . /sys/class/hwmon/hwmon1/in*_input
```

**Comment by rafael2k** [comment]
Thanks @pelwell! Among these 4 ADC inpu6ts, are any of those available to the outside world (even if it involves reworking in the board - for experimentation purposes)?

**Comment by pelwell** [comment]
Define available.

**Comment by rafael2k** [comment]
Some pin in RP1 I can tap / solder to outside the chip.

**Comment by pelwell** [comment]
The unused channels will be totally unconnected - just balls on the bottom of the chip. The used channels have pull-up and pull-down resistors that would have to be located and removed - I have schematics, but not the layout.

**Comment by pelwell** [comment]
No they aren't.

**Comment by pelwell** [comment]
I believe that is the case. The bottom of the board under RP1 is so congested that it would be counterproductive to connect any "pins" that aren't needed.

**Comment by rafael2k** [comment]
Where can I find the list of the the used ADC channels? Are they all listed in "vcgencmd pmic_read_adc" output?

**Comment by pelwell** [comment]
The PMIC ADC channels are completely separate - they provide feedback on the various power rails. As I said earlier, the RP1 ADCs are readable from `/sys/class/hwmon/hwmon1/in*_input`.

**Comment by rafael2k** [comment]
Sorry the mix-up from my side. So in your opinion, is having an externally accessible ADC in the Pi 5, be it using any PMIC ADC or RP1 ADC, something feasible to pursue using amateur-grade lab equipment? 

Or better I just keep using an ATTiny for my analog readings, connected over i2c...

**Comment by pelwell** [comment]
Although much is possible with enough information and soldering skills, I can't recommend butchering a Pi 5 in a way I wouldn't feel comfortable doing myself (or asking one of our hardware guys to do for me).

**Comment by rafael2k** [comment]
Fair enough. Thanks @pelwell!
: )

**Comment by rafael2k** [comment]
Last question - Which is the purpose of the used RP1 ADC lines? 

These are the ones I can read from these device files, right?
/sys/class/hwmon/hwmon1/in*_input

**Comment by pelwell** [comment]
VBUS monitoring, and RAM size detection.
