### ISSUE TITLE
Why redirect STDOUT of pinctrl "e.g. pinctrl poll 5 > out.txt" not work?

### ISSUE THREAD

**Issue by thorsten-l** [raspberrypi/utils#84]
I tried to open a pipe to pinctrl, but even a simple redirect to a file does not work. 
e.g. pinctrl poll 5 > out.txt 
out.txt length ist always zero.

If "pinctrl poll 5" is started without redirect stdout, everything works fine as expected.

btw "pinctrl > out.txt" works fine. May be a "fflush(stdout)" in after line 309 in pinctrl.c would be a solution.

**Comment by thorsten-l** [comment]
A "fflush(stdout)" in after line 309 in pinctrl.c IS the solution! 
Should is do a merge request? - for a single line of code ... :)

**Comment by pelwell** [comment]
Yes, if you want. Otherwise, I'll get round to it eventually.
